var GAME_LEVELS = [
  ["                                                                          PP    ",
   "                                                                         PuuP   ",
   "                                                             o          PuuuuP  ",
   "                                   Q                                    PuuuuP  ",
   "                                                                    xxxxxxxxxxxx",
   "                          o                   o             yyy                 ",
   "                                                            xxx                 ",
   "                                             yyy      o                 yyy     ",
   "                                             xxx                        xxx     ",
   "                        yyy                                                     ",
   "               o        xxx           yyy            yyy           yyy          ",
   "                      xx              xxx            xxx           xxx      xx  ",
   "  xx                                                                         x  ",
   "  x                           yyy                            yyy             x  ",
   "  x       yy  yyy  yy         xxx                            xxx          xxxx  ",
   "  x       xx  xxx  xx                                              xx        x  ",
   "  x @     xxvvxxx!!xx                                            xxxxxx   G  x  ",
   "  xxxxxxxxxx!!xxxxxxxx   xxxx     xxxx             xxxx    xxxxxxx   xxxxxxxxx  ",
   "                     x   x  x     x  x             x  x    x                    ",
   "                     x!!!x  x!!!!!x  x!!!!!!!!!!!!!x  xxxxxx                    ",
   "                     xxxxx  x!!!!!x  xxxxxxxxxxxxxxx                            ",
   "                            xxxxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                          o            o                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                    o    xxx           xx                     ",
   "                                                                                    vvvvvxx                   ",
   "                                                                                   v|v|v|xxx                  ",
   "                                                                          |    xxxxv|v|v|xxxx                 ",
   "                                                    v              xxx         xv           x                 ",
   "                                                          o                    x            x                 ",
   "                                                                               x      G     x                 ",
   "                                                                            xxxx    xxxxxxxxx  Q            v ",
   "                                                         xxxx             xxxx!!                              ",
   "                                                                       xxxxxxxxxxxx                           ",
   "                                                                           x           x    xxxxxxx           ",
   "                                                          o              o x                               xxx",
   "                                               xxx                         xxxxxx            =                ",
   "@                                                                              xxxxx                   o      ",
   "x                                                       xxxxx            xxx      xxxx                        ",
   "xx                                                                                  xxxx      xxxxxxxxxxxxxxxx",
   "xxx                                                              xx  xx                xx         xxxxxxxxxxxx",
   "xxxx                                                           xxxxvvxxxx              xxxx       x    PPxxxxx",
   "xxxxx                                                        xxxxxx!!xxxxxx         Q  xxxxx      x   PuuPxxxx",
   "xxxxxx                   o            o                    xxxxxxxxvvxxxxxxxx          xxxxxx        PuuuuPxxx",
   "xxxxxxx      v                  v                   o    xxxxxxxxxx!!xxxxxxxxxx        xxxxxxx       PuuuuPxxx",
   "xxxxxxxx                                              xxxxxxxxxxxxxvvxxxxxxxxxxxxx     xxxxxxxx      xxxxxxxxx",
   "xxxxxxxxx             xxxxxx         xxxx        xxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxxxxxx!!xxxxxxxxx             x",
   "xxxxxxxxxx          xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!xxxxxxx             x",
   "xxxxxxxxxxx       xxxxxxx!!!!!v!!!!!!!v!!!!!!!v!!!!!!!!v!!xxxxx!!!!!!!!!!!!xxxxxxxxxxxxx!!vxxxxxxxxxxxxxvvvxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!"],
  ["                               x                        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  @                            x                        v   v   v   v   v   v   v   v   v   v   v             ",
   "yyyyyyyyy                      x                          v   v   v   v   v   v   v   v   v   v      PP       ",
   "xxxxxxxxx                      x                                                                    PuuP      ",
   "                               x                                                                   PuuuuP     ",
   "                               x                                                                   PuuuuP     ",
   "        yyyyyyyy               x               Q        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   o    xxxxxxxx               x                                                                              ",
   "                               x                                                                              ",
   "                               x                                                                              ",
   "yyyyyyyyy           yyyy     yyx              xxx                                                             ",
   "xxxxxxx          xxxxxxx     xxx                 xx         o                                         v       ",
   "xxxxxxxxxx                   x                                         =                                      ",
   "xxxxx                     o  x                                                                                ",
   "xxxxxxxxxxx         xxxx     x                          xxxxxxxxx                                             ",
   "xxxxxx            xxxxxx  o  x                                                                                ",
   "xxxxxx        xxxxxxxxxx     x                                        xxx                                     ",
   "xxxxxx            xxxxxx  o  x                                                                                ",
   "xxxxxxxxxx          xxxx     x                                                                    o           ",
   "xxxxxxxxxxxxx     xxxxxx  o  x     o             =                                xxxx                        ",
   "v            o    o          x                                                                                ",
   "                          o  x                                                 o                xxxxxxxxxxxxxx",
   "              yyyy           x                                  xxx                                  v       v",
   "            yyyyyyy       o  x                                                 G    o      xx                 ",
   "             yyxyy           x    xxx                                                    xx              v    ",
   "               x             xvvvvvvvvvvv                  o                yyyyyy                            ",
   "               xx            x!!!!!!!!!!!     xxxx                        yyyyyyyyyyyy                v      v",
   "      yyyyyyyyyyyyyyyyyyyyyyyx!!!!!!!!!!                                  yyyxyyyy              xxxxxxxxxxxxxx",
   "      xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!                                     yyxy                              ",
   "                                                    xxxxxxxxxxxxxxxx       o  xy                              ",
   "                                                                             xxxxxxxxxxxxxx                   ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                             xxxx                  xxx            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               x              o                   ",
   "                xx   o                                                    x          o                        ",
   "                xx o Q o                                                  xx Q                 o              ",
   "                xx   o                                                    xxxxxxxxxxxxxxxxxxx                 ",
   "                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                                  ",
   "                                                                                             o                    ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                            o                                     ",
   "                                                                                           gsssggssgsgsss         ",
   "                                                             o                                                    ",
   "                                                                     ssg   sss   gss                              ",
   "                        Q                                            ggssssgsss!sgssgs     ssssg                  ",
   "                                                                     s        svs  |       s                      ",
   "               |                       v                    xxx      sssg                gss                      ",
   "                       ssss                            o    !!!      g   g            o    g       sgss           ",
   "                                                                     s!!!                  s                      ",
   "                                                                     gsgsggsss             g                      ",
   "                               ggss                                  s                 sssgsssss                  ",
   "                                          sgs         sgs   sss   gssg               ss                           ",
   "                                                      ssgs!gssss!sggss            gss                             ",
   "                      ssgs                            g v                     gsgs                                ",
   "                            o                       sss                   sggs             sgss                   ",
   "                                                      s              gsssg                                        ",
   "                                                      g           sgsg                                            ",
   "                           sgs                        sgss           s                                            ",
   "              o                          o            g              s          PP                 sgss           ",
   "                                               sssgssss              s         PuuP                               ",
   "                                                            G   ssggss        PuuuuP                              ",
   "            sgssg      sgg     gss                              !v!!v!v       PuuuuP     o   o               o    ",
   "         ggss          sgs     sgs     gsgss        gssgssssssgsssggsg||      ssgssgsgsgggsssssgg       gsgssggsss",
   "  @   ssgsssg!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!s        !!!!!!!!g!!!!!!!!s|v|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!g!!!!!!!!!!!!!!!!s!!!!!!!!s!vv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsgsggsgsssgsssgsss!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
